name: Publish Docker Image

on:
  push:
    tags:
      - '*'

jobs:
  push_to_ecr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      env:
        AWS_REGION: ${{ env.AWS_REGION }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ secrets.ECR_REPOSITORY_URI }}:api-${{ github.ref_name }}
        cache-from: type=registry,ref=${{ secrets.ECR_REPOSITORY_URI }}:api-build-cache
        cache-to: type=registry,ref=${{ secrets.ECR_REPOSITORY_URI }}:api-build-cache,mode=max

        # cache-from: type=local,src=/tmp/.buildx-cache
        # cache-to: type=local,dest=/tmp/.buildx-cache
