name: Publish Docker Image

on:
  push:
    tags:
      - '*'

jobs:
  push_to_ecr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      # - name: Cache Docker layers
      #   uses: actions/cache@v3
      #   with:
      #     path: /tmp/.buildx-cache
      #     key: ${{ runner.os }}-buildx-${{ github.sha }}
      #     restore-keys: |
      #       ${{ runner.os }}-buildx-

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io/${{ github.repository }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ vars.ECR_REPOSITORY_URI }}:api-${{ github.ref_name }}
          # because first letter of my username is in uppercase it can't use ${{ github.repository }} context
          cache-from: type=registry,ref=ghcr.io/maders/fragmenty-api:buildcache
          cache-to: type=registry,ref=ghcr.io/maders/fragmenty-api:buildcache,mode=max

          # cache-from: type=local,src=/tmp/.buildx-cache
          # cache-to: type=local,dest=/tmp/.buildx-cache,mode=max

          # cache-from: type=gha
          # cache-to: type=gha,mode=max

          # cache-from: type=registry,ref=${{ vars.ECR_REPOSITORY_URI }}:api-build-cache
          # cache-to: type=registry,ref=${{ vars.ECR_REPOSITORY_URI }}:api-build-cache,mode=max
